/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package managementsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class club_i_add extends javax.swing.JFrame {

    /**
     * Creates new form club_i_add
     */
    public club_i_add() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setVisible(true);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dristi = new javax.swing.JCheckBox();
        literary = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        name = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        mob = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ieee = new javax.swing.JCheckBox();
        drama3 = new javax.swing.JCheckBox();
        gfg = new javax.swing.JCheckBox();
        dance = new javax.swing.JCheckBox();
        photo = new javax.swing.JCheckBox();
        coding = new javax.swing.JCheckBox();
        ed = new javax.swing.JCheckBox();
        nss = new javax.swing.JCheckBox();
        music = new javax.swing.JCheckBox();
        codechef = new javax.swing.JCheckBox();
        uba = new javax.swing.JCheckBox();
        robotics = new javax.swing.JCheckBox();
        post = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Details");

        dristi.setText("Dristi");
        dristi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dristiActionPerformed(evt);
            }
        });

        literary.setText("Literary Society");
        literary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                literaryActionPerformed(evt);
            }
        });

        jLabel8.setText("Select ");

        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("INCHARGE REGISTRATION");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("BACK");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel1.setText("ID");

        jLabel4.setText("Name");

        jLabel5.setText("Email");

        jLabel6.setText("Mob No.");

        jLabel7.setText("SELECT");

        ieee.setText("IEEE");

        drama3.setText("Drama Club");
        drama3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drama3ActionPerformed(evt);
            }
        });

        gfg.setText("GeeksforGeeks");

        dance.setText("Dance Club");

        photo.setText("Photography");

        coding.setText("Coding Society");

        ed.setText("ED ");

        nss.setText("NSS");

        music.setText("Music Club");

        codechef.setText("CodeChef");

        uba.setText("Unnat Bharat ");
        uba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubaActionPerformed(evt);
            }
        });

        robotics.setText("Robitics");
        robotics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roboticsActionPerformed(evt);
            }
        });

        jLabel9.setText("Post");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(post, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dance)
                                .addComponent(ieee)
                                .addComponent(nss)
                                .addComponent(photo)
                                .addComponent(codechef))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(drama3)
                                        .addComponent(gfg)
                                        .addComponent(ed)
                                        .addComponent(coding))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(literary)
                                        .addComponent(music)
                                        .addComponent(uba)
                                        .addComponent(dristi)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addComponent(robotics)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(id)
                        .addComponent(name)
                        .addComponent(email)
                        .addComponent(mob, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 43, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(80, 80, 80))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(mob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(post, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ieee)
                    .addComponent(gfg)
                    .addComponent(music))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dance)
                    .addComponent(drama3)
                    .addComponent(literary))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(photo)
                    .addComponent(ed)
                    .addComponent(uba))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nss)
                    .addComponent(coding)
                    .addComponent(dristi))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codechef)
                    .addComponent(robotics))
                .addGap(16, 16, 16)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dristiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dristiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dristiActionPerformed

    private void literaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_literaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_literaryActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("java.sql.DriverManager");
            Connection conn = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/universitymanagementsystem", "root" , "");
            Statement st = (Statement)conn.createStatement();
            String sql = "INSERT INTO `club_i_reg` VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";

            PreparedStatement ptstat = conn.prepareStatement(sql);
            ptstat.setString(1,id.getText());
            ptstat.setString(2,name.getText() );
            ptstat.setString(3, email.getText());
            ptstat.setString(4,mob.getText() );
            ptstat.setString(5,post.getText() );
            ptstat.setBoolean(6, ieee.isSelected());
            ptstat.setBoolean(7, gfg.isSelected());
            ptstat.setBoolean(8, dance.isSelected());
            ptstat.setBoolean(9, music.isSelected());
            ptstat.setBoolean(10, drama3.isSelected());
            ptstat.setBoolean(11, literary.isSelected());
            ptstat.setBoolean(12, photo.isSelected());
            ptstat.setBoolean(13, ed.isSelected());
            ptstat.setBoolean(14, uba.isSelected());
            ptstat.setBoolean(15, nss.isSelected());
            ptstat.setBoolean(16, coding.isSelected());
            ptstat.setBoolean(17, dristi.isSelected());
            ptstat.setBoolean(18, codechef.isSelected());
            ptstat.setBoolean(19, robotics.isSelected());

            ptstat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Saved");
            conn.close();

        }
        catch( Exception e)
        {
            JOptionPane.showMessageDialog(null, "Error while establishing connection");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        clubs_i_page obj = new clubs_i_page();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void drama3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drama3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drama3ActionPerformed

    private void ubaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ubaActionPerformed

    private void roboticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roboticsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roboticsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(club_i_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(club_i_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(club_i_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(club_i_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new club_i_add().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox codechef;
    private javax.swing.JCheckBox coding;
    private javax.swing.JCheckBox dance;
    private javax.swing.JCheckBox drama;
    private javax.swing.JCheckBox drama1;
    private javax.swing.JCheckBox drama2;
    private javax.swing.JCheckBox drama3;
    private javax.swing.JCheckBox dristi;
    private javax.swing.JCheckBox ed;
    private javax.swing.JTextField email;
    private javax.swing.JCheckBox gfg;
    private javax.swing.JTextField id;
    private javax.swing.JCheckBox ieee;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JCheckBox literary;
    private javax.swing.JTextField mob;
    private javax.swing.JCheckBox music;
    private javax.swing.JTextField name;
    private javax.swing.JCheckBox nss;
    private javax.swing.JCheckBox photo;
    private javax.swing.JTextField post;
    private javax.swing.JCheckBox robotics;
    private javax.swing.JCheckBox uba;
    // End of variables declaration//GEN-END:variables
}
